config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :sports
  root to: 'home#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
# frozen_string_literal: true

class Player < ApplicationRecord
  has_many :transfers, dependent: :destroy
  has_many :teams, through: :transfers

  validates :name, presence: true
end

app/models/sport.rb
# frozen_string_literal: true

class Sport < ApplicationRecord
  validates :name, presence: true
end

app/models/team.rb
# frozen_string_literal: true

class Team < ApplicationRecord
  has_many :transfers, dependent: :destroy
  has_many :players, through: :transfers

  validates :name, presence: true
end

app/models/transfer.rb
# frozen_string_literal: true

class Transfer < ApplicationRecord
  belongs_to :player
  belongs_to :team
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController

  def index
  end
end

app/controllers/sports_controller.rb
# frozen_string_literal: true

class SportsController < ApplicationController

  before_action :set_sport, only: %i[show edit update destroy]

  def index
    @sports = Sport.order(:name)
  end

  def show
  end

  def new
    @sport = Sport.new
  end

  def create
    @sport = Sport.new(create_params)
    if @sport.save
      redirect_to sport_path(@sport)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @sport.update(update_params)
      redirect_to sport_path(@sport)
    else
      render :edit
    end
  end

  def destroy
    if @sport.destroy
      redirect_to sports_path
    else
      redirect_to sport_path(@sport)
    end
  end

  private

  def set_sport
    @sport = Sport.find(params[:id])
  end

  def create_params
    params.require(:sport).permit(:name)
  end

  def update_params
    create_params
  end

end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.slim
h1 Hello World

app/views/layouts/_aside.html.slim
aside#aside
  = link_to('Sports', sports_path)

app/views/layouts/_footer.html.slim
footer

app/views/layouts/_header.html.slim
header
  .right
    = fa_icon('bars 3x', id: 'bar')
    = link_to(fa_icon('home 3x'), root_path)
  .left
    - if user_signed_in?
      => link_to(fa_icon('sign-out 3x'), destroy_user_session_path, method: 'delete')
      => link_to(fa_icon('user 3x'), edit_user_registration_path)
      = current_user.email
    - else
      = link_to(fa_icon('sign-in 3x'), new_user_session_path)
      = link_to((fa_icon('user-plus 3x')), new_user_registration_path)

app/views/layouts/_nav.html.slim
nav#nav

app/views/layouts/application.html.slim
doctype html
html
  head
    title Dorpsheets
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    main
      article
        = yield
      = render 'layouts/nav'
      = render 'layouts/aside'
    = render 'layouts/footer'
    = javascript_include_tag "main"

app/views/sports/_form.html.slim
= simple_form_for(sport) do |f|
  = f.input(:name)
  = f.submit
=< link_to('Back', :back)

app/views/sports/_sport.html.slim
tr
  td = link_to(sport.name, sport_path(sport))
  td = link_to('Edit', edit_sport_path(sport))

app/views/sports/edit.html.slim
= render 'form', sport: @sport

app/views/sports/index.html.slim
= link_to('Add sport', new_sport_path)
table
  thead
    th = 'Name'
  tbody
    = render @sports

app/views/sports/new.html.slim
= render 'form', sport: @sport

app/views/sports/show.html.slim
= @sport.name
=< link_to('Back', :back)